export const POSITIONS = ['Game', 'Analytics', 'DevOps', 'Support', 'Testing']
export const TECHNOLOGIES = [
  'Angular',
  'Python',
  'C',
  'HTML5',
  'Java',
  'Ruby',
  'NodeJS',
  'PHP',
]
export const JOBOFFERS = [
  {
    position: 'Remote Ruby on Rails Developer',
    company: 'Devstock',
    city: 'Warszawa',
    salaryMin: 5000,
    salaryMax: 10000,
    technology: 'Ruby',
    remote: false,
    expLvl: 'Mid',
  },
  {
    position: 'Java Developer',
    company: 'Microsoft',
    city: 'Gdańsk',
    salaryMin: 2000,
    salaryMax: 5000,
    technology: 'Java',
    remote: false,
    expLvl: 'Mid',
  },
  {
    position: 'Senior Python Developer',
    company: 'AI-master',
    city: 'Warszawa',
    salaryMin: 10000,
    salaryMax: 15000,
    technology: 'Python',
    remote: true,
    expLvl: 'Senior',
  },
  {
    position: 'Junior PHP Developer',
    company: 'Devstock',
    city: 'Warszawa',
    salaryMin: 3000,
    salaryMax: 5000,
    technology: 'PHP',
    remote: true,
    expLvl: 'Junior',
  },
  {
    position: 'Senior C developer',
    company: 'Automoto',
    city: 'Kraków',
    salaryMin: 10000,
    salaryMax: 20000,
    technology: 'C',
    remote: false,
    expLvl: 'Senior',
  },
  {
    position: 'Angular Developer',
    company: 'Pyszne.pl',
    city: 'Warszawa',
    salaryMin: 5000,
    salaryMax: 10000,
    technology: 'Angular',
    remote: true,
    expLvl: 'Mid',
  },
  {
    position: 'Senior NodeJS Developer',
    company: 'Politech',
    city: 'Wrocław',
    salaryMin: 12000,
    salaryMax: 18000,
    technology: 'NodeJS',
    remote: false,
    expLvl: 'Senior',
  },
]
