export const POSITIONS = ['Game', 'Analytics', 'DevOps', 'Support', 'Testing']
export const TECHNOLOGIES = [
  'Angular',
  'Python',
  'C',
  'HTML5',
  'Java',
  'Ruby',
  'NodeJS',
  'PHP',
]
export const JOBOFFERS = [
  {
    id: 0,
    position: 'Remote Ruby on Rails Developer',
    company: 'Devstock',
    city: 'Warszawa',
    salaryMin: 5000,
    salaryMax: 10000,
    technology: 'Ruby',
    additionalTech: 'AWS',
    remote: true,
    expLvl: 'Mid',
    positionName: 'Analytics',
    years: 4,
  },
  {
    id: 1,
    position: 'Java Developer',
    company: 'Microsoft',
    city: 'Gdańsk',
    salaryMin: 2000,
    salaryMax: 5000,
    technology: 'Java',
    additionalTech: 'Docker',
    remote: false,
    expLvl: 'Mid',
    positionName: 'DevOps',
    years: 5,
  },
  {
    id: 2,
    position: 'Senior Python Developer',
    company: 'AI-master',
    city: 'Warszawa',
    salaryMin: 10000,
    salaryMax: 15000,
    technology: 'Python',
    additionalTech: 'Docker',
    remote: true,
    expLvl: 'Senior',
    positionName: 'Support',
    years: 7,
  },
  {
    id: 3,
    position: 'Junior PHP Developer',
    company: 'Devstock',
    city: 'Warszawa',
    salaryMin: 3000,
    salaryMax: 5000,
    technology: 'PHP',
    additionalTech: 'AWS',
    remote: true,
    expLvl: 'Junior',
    positionName: 'DevOps',
    years: 1,
  },
  {
    id: 4,
    position: 'Senior C developer',
    company: 'Automoto',
    city: 'Kraków',
    salaryMin: 10000,
    salaryMax: 20000,
    technology: 'C',
    additionalTech: 'Kubernetes',
    remote: false,
    expLvl: 'Senior',
    positionName: 'Game',
    years: 8,
  },
  {
    id: 5,
    position: 'Angular Developer',
    company: 'Pyszne.pl',
    city: 'Warszawa',
    salaryMin: 5000,
    salaryMax: 10000,
    technology: 'Angular',
    additionalTech: 'Css',
    remote: true,
    expLvl: 'Mid',
    positionName: 'Analytics',
    years: 5,
  },
  {
    id: 6,
    position: 'Senior NodeJS Developer',
    company: 'Politech',
    city: 'Wrocław',
    salaryMin: 12000,
    salaryMax: 18000,
    technology: 'NodeJS',
    additionalTech: 'AWS',
    remote: false,
    expLvl: 'Senior',
    positionName: 'DevOps',
    years: 6,
  },
  {
    id: 7,
    position: 'Remote C Developer',
    company: 'CD PROJECT',
    city: 'Katowice',
    technology: 'C',
    additionalTech: '',
    remote: true,
    expLvl: 'Mid',
    positionName: 'Game',
    years: 4,
  },
]

export const SENIORITY = ['Junior', 'Mid', 'Senior']

export const SORTBY = ['Lowest salary', 'Highest salary']

export const USERINFO = [
  {
    title: 'Your role and responsibilities',
    content: [
      'Building API',
      'Working on V4 of the product',
      'Support on V3 ',
      'Expanding existing product sections in separate web services',
    ],
  },
  {
    title: 'Your profile and required skills',
    content: [
      'Building API',
      'Working on V4 of the product',
      'Support on V3 ',
      'Expanding existing product sections in separate web services',
    ],
  },
  {
    title: 'Nice to have',
    content: [
      'Building API',
      'Working on V4 of the product',
      'Support on V3 ',
      'Expanding existing product sections in separate web services',
    ],
  },
  {
    title: 'What can we offer?',
    content: [
      '💚 7-hours working day',
      'Private healthcare',
      'Multisport card 🇬🇧 English lessons with a Native Speaker 👨‍💻',
      'Apple equipment (MacBook) 👨‍🎓',
    ],
  },
]
export const COMPANYINFO =
  'Flying Bisons is one of the leading Digital Consulting companies. Our mission is to co-create valuable and innovative digital products for millions of people. We work with the biggest brands (IKEA, Mercedes-AMG, Polpharma Biologics, KFC, NC+, Park of Poland, Enel-med, Hebe) and disruptive startups (Booksy, Devskiller, Muscat, Vaiot). We work in end-to-end process (Research & Strategy, Design, Development, Analytics & Optimization) to have a real impact on business results. '

export const CONDITIONS =
  'The Administrator of your personal data is the DEVmanufacture with its registered office undefined, ul. undefined. Your personal data will be processed for the purpose of current and future business contacts, ongoing cooperation. We plan to process your personal data for the duration of our cooperation. Under the GDPR, you have certain rights in connection with the processing of your personal data: a. you have a right to be informed what personal data concerning you are processed by us and to received copies thereof (so called right of access). The first copy of the data is free of any charges, whereas we may charge a fee for each subsequent copy thereof; b. if the processed data become outdated or incomplete (or otherwise inaccurate), you have the right to rectify thereof; c. in certain cases you may request us to delete your personal data, e.g. when we no longer need your data for the purposes communicated to you; when you effectively withdraw your consent for data processing (unless we are authorized to process your data under a different legal basis); if the processing would be contrary to laws; or if we are obliged to delete the data by operation of law; d. you have a right to lodge a complaint with the President of the Office of Personal Data Protection if you determine that the processing of your personal data breaches the GDPR. e. in the event that we process your personal data on the basis of your consent granted to us to process your personal data, or to perform the agreement concluded with you, you may transfer your data to another controller; f. if you determine that the personal data are inaccurate, processed contrary to laws, or that we do not need certain data, you may also request that we do not carry out any operations on the data for a given period of time required by you (e.g. to verify the accuracy of data or seek claims), but solely store them.'
